version: 2
jobs:
  build:
    working_directory: ~/w
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn tslint
      - run: yarn jest
      - run: yarn flow check
      - run: yarn build
